Vagrant.configure("2") do |config|

  config.vm.box = 'generic/ubuntu1804'
  config.vm.network :forwarded_port, guest: 8080, host: 8080
    config.vm.provision "docker" do |d|
      d.pull_images "jenkinsci/blueocean:latest"
      d.run "jenkinsci/blueocean",
      args: "-u root \
            -p 8080:8080 \
            -v jenkins-data:/var/jenkins_home \
            -v /var/run/docker.sock:/var/run/docker.sock",
      image: "jenkinsci/blueocean:latest"
    end
end