Vagrant.require_version '>= 1.9.3'

Vagrant.configure(2) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.network :forwarded_port, guest: 4000, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    # Install docker
    sudo -i
    apt install -y curl
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    curl -sSL https://get.docker.com/ | sh
    usermod -aG docker $USER
    curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    newgrp docker
  SHELL
end

