node {
   def mvnHome = tool 'M3'

stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git url: 'https://github.com/cmcornejocrespo/webinar-bat-desk.git', branch: 'feature/jbcnconf-2017'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.

   }
   stage('Build') {
      // Run the maven build
      sh "'${mvnHome}/bin/mvn' clean package"
   }

   stage('Run unit tests') {
	// Run the maven test
      sh "'${mvnHome}/bin/mvn' test"
   }

   stage('Run Sonar reports') {
	// Run the maven test
      echo("Sonar reports successfully run");
   }
   stage('Run Integration Tests') {
      // Run integration tests
      sh "'${mvnHome}/bin/mvn' clean verify -Pintegration-tests"
   }
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archiveArtifacts 'bat-desk-common/target/*.jar'
   }
}