Vagrant.require_version '>= 1.9.3'

Vagrant.configure(2) do |config|

  config.vm.box = 'ubuntu/xenial64'
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    # Install docker
    sudo -i
    apt-get update && apt install -y curl
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    curl -sSL https://get.docker.com/ | sh
    usermod -aG docker $USER
    sudo docker run -p 8080:8080 jenkinsci/blueocean
  SHELL
end

